panel/scene.js, panel/webview/ipc.js, panel/webview/page-init.js, panel/webview/scene-manager.js
https://github.com/fireball-x/fireball/issues/45
=> implement scene-view store and restore

panel/webview/scene-manager.js
=> Remove test scene (cocos logo)

panel/webview/editor-engine.js
=> remove _emptySgScene

panel/webview/editor-engine.js
=> design resolution should be inited before canvas size

panel/webview/editor-engine.js, panel/webview/scene-view.js
@jareguo 
fireball-x/fireball#491
=> hitTest to component

main.js
update fireball-x/fireball#532
=> add defaultType and assetType for meta

panel/scene-view/scene-view.js, panel/scene.js
=> resize scene when show panel

package.json, panel/scene-ipc-handler.js, panel/scene-view/scene-view.js, panel/scene.js, test/renderer/animation-messages.js
=> add animation messages

main.js
update fireball-x/fireball#108
=> title will update with undo changed

panel/scene-view/engine-events.js, panel/scene-view/scene-view.js, panel/scene.js
需求：调用 cc.engine.setDesignResolutionSize 会改变 scene view 中线框大小
fireball-x/fireball#553
@jareguo
=> change scene resolution when trigger design-resolution-changed event

panel/scene-view/engine-events.js, panel/scene-view/scene-view.js, panel/scene.html, panel/scene.js
=> refine scene view

panel/scene-ipc-handler.js, panel/scene-view/editor-engine.js
=> hit test need test node and components

package.json
update fireball-x/fireball#587
=> fixed scene view shortcut invalid

panel/scene-ipc-handler.js, panel/scene-view/scene-manager.js, panel/scene.js
update fireball-x/fireball#591
@jwu
=> fixed compile script failed

panel/scene-undo.js, panel/scene.js
=> support undo created objects

panel/scene-undo.js, panel/scene-view/scene-view.js, panel/scene.js
=> add delete undo record

package.json, panel/scene-undo.js, panel/scene.js
=> support undo-cancel

main.js, package.json, panel/scene-undo.js, panel/scene-view/scene-view.js, panel/scene.js
update fireball-x/fireball#165
=> detect scene dirty and save it

main.js
update fireball-x/fireball#165
=> fix cancel save will report error

panel/scene.js
=> record create empty node in undo

panel/scene.js
update fireball-x/fireball#478
=> reply time should be wrapped

panel/scene-undo.js
=> also record comps when delete node for undo

panel/scene-view/editor-engine.js
=> add late-update event

package.json, panel/scene.js
update fireball-x/fireball#677
@jwu
=> add scene:query-node-functions message

package.json, panel/scene.js
update fireball-x/fireball#635
=> add scene:is-child-class-of

panel/scene-undo.js
=> update api of record-object

main.js, panel/scene.js
update fireball-x/fireball#500
=> support db:// protocol

main.js, package.json, panel/scene.js
@jwu please review
for https://github.com/fireball-x/fireball/issues/725
=> add copy and paste for hierarchy

package.json, panel/scene-view/editor-engine.js, panel/scene-view/sandbox.js, panel/scene.js
update fireball-x/fireball#629
=> add create-node-by-prefab message

panel/scene-view/scene-view.js
update fireball-x/fireball#500
=> remove asset-library initialize code from scene-view

panel/scene.js
update fireball-x/fireball#629
=> allow scene:add-component choose active node if nodeID is null

panel/scene.js
=> fixed EngineEvents unregister

panel/scene.js
for https://github.com/fireball-x/fireball/issues/795
=> unlink prefab created by menu

panel/scene.js
update fireball-x/fireball#145
=> use waitForReply formation

panel/scene-view/scene-view.js
update fireball-x/fireball#569
@jwu
=> shift key operation should have biggest priority

panel/scene.js
update fireball-x/fireball#650
=> more information for query-node-info message

panel/scene.js
update fireball-x/fireball#663
=> set _runDashboard to false when cancel scene save

panel/scene.js
update fireball-x/fireball#650
=> use getClassById

main.js, panel/scene.js
- update fireball-x/fireball#831
- update fireball-x/fireball#832
=> Add warnning message when add or remove component

panel/scene.js
update fireball-x/fireball#828
@jwu
=> query-animation-node 需向上查询 animation node

package.json, panel/scene.js
update fireball-x/fireball#812
@jwu
=> add scene:new-clip message

panel/scene.js
=> change cc.EScene to cc.Scene

package.json, panel/scene.js
update fireball-x/fireball#817
=> add ipc message scene:reset-property

panel/scene.js, test/renderer/animation-messages.js
https://github.com/fireball-x/fireball/issues/649
=> cc.AnimationComponent Renamed cc.Animation

panel/scene-utils/index.js, panel/scene-view.js, panel/scene.html, panel/scene.js
update fireball-x/fireball#613
=> move more functions from scene, scene-view to _Scene

panel/scene-utils/anim-utils.js, panel/scene-utils/index.html, panel/scene-utils/index.js, panel/scene.js
=> move animation functions from scene to anim utils

main.js, panel/scene-utils/index.js, panel/scene.js
update fireball-x/fireball#942
=> try to load last edit scene

panel/scene-view.js
update fireball-x/fireball#967
@jwu
=> add mouse right key for move scene

panel/scene-utils/index.js, panel/scene-utils/scene-undo.js, panel/scene.js
update fireball-x/fireball#865
=> refine scene undo for delete command

panel/scene-utils/index.js, panel/scene-utils/scene-undo.js
update fireball-x/fireball#865
=> support undo redo for add and remove component

panel/scene-utils/index.js, panel/scene.js
update fireball-x/fireball#965
@jwu
=> fireball-x/fireball#965

panel/scene-utils/index.js
=> fixed recordNodeChanged error

panel/scene-utils/engine-extends/editor-engine.js
update fireball-x/fireball#996
@jwu
=> hit test should check node and component active

panel/scene-utils/anim-utils.js, panel/scene-utils/index.js, panel/scene.js
=> fixed bugs

panel/scene-view.js
update fireball-x/fireball#1060
=> use Editor.Math

panel/scene-utils/index.js
update fireball-x/fireball#1032
=> create node will adjust position for precision
